import type {Metadata} from "next";
import "./globals.css";
import {NextIntlClientProvider, hasLocale} from "next-intl";
import {routing} from "@/i18n/routing";
import {notFound} from "next/navigation";
import {Inter, Merriweather, Courier_Prime} from "next/font/google";
import {AuroraBackground} from "@/components/ui/aurora-background";
import {ThemeProvider} from "@/components/theme/theme-provider";
import {Suspense} from "react";
import Footer from "@/components/layout/footer";
import Navigation from "@/components/layout/navigation";
import {SpeedInsights} from "@vercel/speed-insights/next";

const inter = Inter({
    variable: '--font-inter',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

const merriweather = Merriweather({
    variable: '--font-merriweather',
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

const courierprime = Courier_Prime({
    variable: '--font-courier-prime',
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
};

export default async function RootLayout({
                                             children, params
                                         }: Props
                                         //                                    Readonly<{
                                         //     children: React.ReactNode;
                                         // }>
) {
    const {locale} = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${inter.variable} ${merriweather.variable} ${courierprime.variable} antialiased flex min-h-screen flex-col font-inter`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <Suspense fallback={<div>Lade Seite ...</div>}>
                <NextIntlClientProvider>
                    <Navigation/>
                    <main className={'flex-grow w-full pt-16'}>
                        <AuroraBackground>
                            {children}
                            <SpeedInsights />
                        </AuroraBackground>
                    </main>
                    <Footer/>
                </NextIntlClientProvider>
            </Suspense>

        </ThemeProvider>
        </body>
        </html>
    );
}
